### ISSUE TITLE
Error in macro execution 

### ISSUE THREAD

**Issue by sofianekh94** [ruijiehe/CMC_modelling_CST#1]
When runing BuildCMC, from Macro drop down list , i get this error message

![error](https://user-images.githubusercontent.com/71104143/92824713-0c65cf00-f3cf-11ea-8d05-baf23372c113.jpg)

 please help me with this problem

**Comment by ruijiehe** [comment]
> When runing BuildCMC, from Macro drop down list , i get this error message
> 
> ![error](https://user-images.githubusercontent.com/71104143/92824713-0c65cf00-f3cf-11ea-8d05-baf23372c113.jpg)
> 
> please help me with this problem

I can't reproduce this error. Please provide some context: language of system, version of CST, and the parameter list created by CheckParameters.

**Comment by sofianekh94** [comment]
About the information that you required
language of system : English (US)
CST STUDIO SUITE® : Release version 2019.00
parameter list created by CheckParameters 
Alpha           121boolThin        0DE                 23DI                  17HE                 10N                    11wR                 0.10000000000000001


 

 

 

-----------------------------------------------------------------

Khelladi Sofiane

PhD student , Amar Telidji University - Laghouat 

Faculty of Technology

Department of Electrical Engineering

Laboratory: LACOSER

------------------------------------------------- 

e-mail 1 : s.khelladi@lagh-univ.dz

e-mail 2 : khelledisofiane@yahoo.com

| 
Tel:            + 213 6 98 34 60 80

                    + 213 6 59 67 20 74

 --------------------------------------------------------------

 
 |


 

    On Friday, September 11, 2020, 02:57:52 PM GMT+2, RH <notifications@github.com> wrote:  
 
 



When runing BuildCMC, from Macro drop down list , i get this error message



please help me with this problem


I can't reproduce this error. Please provide some context: language of system, version of CST, and the parameter list created by CheckParameters.

**Comment by sofianekh94** [comment]
Dear Ruijie He.
The issue was resolved after changing the system language.
Thank you I am very grateful

**Comment by ruijiehe** [comment]
You are welcome.
It's interesting the robustness of the script is subject to system language, I may have a look into this phenomenon.
Wish you good luck with your research.

**Comment by sofianekh94** [comment]
Dear Ruijie He.I hope you are well
First of all I renew my gratitude to you for the very useful MACRO you provided me with.On the other hand, I have a question to ask you concerning the dimensions of the core of the CMC. I've noticed that after running Build a CMC with a given core , the dimensions of the later slightly differ from the ones introduced in the "check Parameters "section (difference of (± 0.2mm)) . I wanted to know is this difference refer to the coating of the core.
Looking forward to receiving your reply and thank you in advance.  


 

 

-----------------------------------------------------------------

Khelladi Sofiane

PhD student , Amar Telidji University - Laghouat 

Faculty of Technology

Department of Electrical Engineering

Laboratory: LACOSER

------------------------------------------------- 

e-mail 1 : s.khelladi@lagh-univ.dz

e-mail 2 : khelledisofiane@yahoo.com

| 
Tel:            + 213 6 98 34 60 80

                    + 213 6 59 67 20 74

 --------------------------------------------------------------

 
 |

**Comment by ruijiehe** [comment]
Yes, there’s is coating with thickness of 0.1mm, to avoid intersections of
core and wire
